### ISSUE TITLE
Trabajo Mantenimiento PMD.

### ISSUE THREAD

**Issue by SantosSanzJ** [SantosSanzJ/2022-ISO2-C04-ET.02.04#2]
Arreglar los problemas que se muestra en el PMD y si alguno se dedice no arreglar, razonarlo.

**Comment by GonzaloPdelaB** [comment]
Hemos pensado que a pesar de que salte "UselessParentheses", es mejor mantenerlos puesto que es una operación algo compleja y los paréntesis facilitan su comprensión.

**Comment by GonzaloPdelaB** [comment]
Solucionado junto con el JavaDoc en el commit "5dc3241f0fdc07aa5b4e9d6c3e243438e52d8409"
